OnlineClothStore/Models/Vendor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace OnlineClothStore.Models
{
    public class Vendor
    {
        public int VendorId { get; set; }
        [Required]
        [Display(Name = "Name")]
        public string VendorName { get; set; }
        [Required]
        [Display(Name = "Password")]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 10)]
        [DataType(DataType.Password)]
        public string VendorPassword { get; set; }
        [Required]
        [Display(Name = "Email")]
        [EmailAddress]
        public string VendorEmail { get; set; }
        [Required]
        [Display(Name = "Mobile Number")]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Invalid Mobile Number")]
        public string VendorPhone { get; set; }
        [Required]
        [Display(Name = "Address")]
        public string VendorAddress { get; set; }
        public float VWalletBalance { get; set; }
    }
}

OnlineClothStore/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineClothStore.Models;

namespace OnlineClothStore.Controllers
{
    public class OrdersController : Controller
    {
        private OnlineClothStoreDBContext db = new OnlineClothStoreDBContext();
        // GET: Orders
        public ActionResult Index()
        {
            return View(db.Order.ToList());
        }


        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }
        public ActionResult CustomerHistory(string email)
        {

            if (email == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int CustomerId = (int)db.Customer.Where(c => c.CustomerEmail == email).Select(c => c.CustomerId).FirstOrDefault();

            IQueryable<Order> order = db.Order.Where(o => o.CustomerId == CustomerId);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order.ToList());
        }
        public ActionResult VendorHistory(string email)
        {

            if (email == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int VendorId = (int)db.Vendor.Where(v => v.VendorEmail == email).Select(v => v.VendorId).FirstOrDefault();

            IQueryable<Order> order = db.Order.Where(o => o.VendorId == VendorId);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order.ToList());
        }
        public ActionResult VendorPendingOrders(string email)
        {

            if (email == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int VendorId = (int)db.Vendor.Where(v => v.VendorEmail == email).Select(v => v.VendorId).FirstOrDefault();

            IQueryable<Order> order = db.Order.Where(o => (o.VendorId == VendorId&&o.OrderStatus=="Pending"));
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order.ToList());
        }
        public ActionResult OrdersByVendorId(string email)
        {
            if (email == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int VendorId = (int)db.Vendor.Where(v => v.VendorEmail == email).Select(v => v.VendorId).FirstOrDefault();

            IQueryable<Order> order = db.Order.Where(o => (o.VendorId == VendorId));
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order.ToList());
        }

        // GET: Orders/Create
        [Authorize]
        public ActionResult Create()
        {
            
            Order order = TempData["orderDetails"] as Order;
            TempData["ToPassOrderDetails"] = order;
            return View(order);
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "OrderId,CustomerId,VendorId,ProductId,ProductQuantity,OrderStatus,OrderDate,OrderTotal")] Order order)
        {
            string CusEmail=Convert.ToString(Request["CustomerEmail"].ToString());
            order.CustomerId = (int)db.Customer.Where(c => c.CustomerEmail == CusEmail).Select(c => c.CustomerId).FirstOrDefault();
            float CusWallet=(float)db.Customer.Where(c => c.CustomerEmail == CusEmail).Select(c => c.CustomerWalletBalance).FirstOrDefault();
            Product product = TempData["currentOrderProduct"] as Product;
            Order storedOrder = TempData["ToPassOrderDetails"] as Order;
            order.OrderStatus = storedOrder.OrderStatus;
            order.ProductId = storedOrder.ProductId;
            order.OrderDate = storedOrder.OrderDate;
            order.VendorId = storedOrder.VendorId;
            order.OrderTotal = order.ProductQuantity * product.ProductPrice;
            if (order.OrderTotal > CusWallet)
            {
                ModelState.AddModelError("","Insufficient Balance.Please Recharge your wallet.");
            }
            if (ModelState.IsValid)
            {
                db.Order.Add(order);
                db.SaveChanges();
                return RedirectToAction("CustomerDashboard","Customers");
            }

            return View(order);
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderId,CustomerId,VendorId,ProductId,ProductQuantity,OrderStatus,OrderDate,OrderTotal")] Order order)
        {
            if (ModelState.IsValid)
            {
                int customerId = order.CustomerId;
                Customer customer = db.Customer.Find(customerId);
                customer.CustomerWalletBalance = customer.CustomerWalletBalance - order.OrderTotal;
                int vendorId = order.VendorId;
                Vendor vendor = db.Vendor.Find(vendorId);
                vendor.VWalletBalance = vendor.VWalletBalance + order.OrderTotal;
                db.Entry(customer).State = EntityState.Modified;
                db.Entry(vendor).State = EntityState.Modified;
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                //return RedirectToAction("Index");
            }
            return View(order);
        }
        // GET: Orders/Edit/5
        public ActionResult EditForDeny(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditForDeny([Bind(Include = "OrderId,CustomerId,VendorId,ProductId,ProductQuantity,OrderStatus,OrderDate,OrderTotal")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                //return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Order.Find(id);
            db.Order.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineClothStore/Controllers/VendorsController.cs
using Microsoft.AspNet.Identity;
using OnlineClothStore.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace OnlineClothStore.Controllers
{
    public class VendorsController : Controller
    {
        private OnlineClothStoreDBContext db = new OnlineClothStoreDBContext();
        private ApplicationDbContext db1 = new ApplicationDbContext();

        // GET: Vendors
        public ActionResult Index()
        {
            return View(db.Vendor.ToList());
        }

        // GET: Vendors/Details/5
        public ActionResult Details(string email)
        {
            if (email == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vendor vendor = (Vendor)db.Vendor.SingleOrDefault(c => c.VendorEmail == email);
            if (vendor == null)
            {
                return HttpNotFound();
            }
            return View(vendor);
        }

        // GET: Vendors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vendors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VendorId,VendorName,VendorPassword,VendorEmail,VendorPhone,VendorAddress,VWalletBalance")] Vendor vendor)
        {
            if (ModelState.IsValid)
            {
                db.Vendor.Add(vendor);
                if (!db1.Users.Any(u => u.Email == vendor.VendorEmail))
                {
                    var store = new Microsoft.AspNet.Identity.EntityFramework.UserStore<ApplicationUser>(db1);
                    var manager = new UserManager<ApplicationUser>(store);
                    var user = new ApplicationUser { UserName = vendor.VendorEmail, Email = vendor.VendorEmail };
                    manager.Create(user, vendor.VendorPassword);
                }
                db.SaveChanges();
                return RedirectToAction("VendorLogin", "Account");
            }

            return View(vendor);
        }

        // GET: Vendors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vendor vendor = db.Vendor.Find(id);
            if (vendor == null)
            {
                return HttpNotFound();
            }
            return View(vendor);
        }

        // POST: Vendors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VendorId,VendorName,VendorPassword,VendorEmail,VendorPhone,VendorAddress,VWalletBalance")] Vendor vendor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vendor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("VendorDashboard");
            }
            return View(vendor);
        }

        // GET: Vendors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vendor vendor = db.Vendor.Find(id);
            if (vendor == null)
            {
                return HttpNotFound();
            }
            return View(vendor);
        }

        // POST: Vendors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vendor vendor = db.Vendor.Find(id);
            db.Vendor.Remove(vendor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult VendorDashboard()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineClothStore/Views/Vendors/Create.cshtml
@model OnlineClothStore.Models.Vendor

@{
    ViewBag.Title = "Welcome to Fashion Hub!!!";
}

@*<body style="background-image: url('../../images/pic2.jpg');background-repeat:no-repeat;background-size:cover">*@
<h2 id="signtitle">@ViewBag.Title</h2>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.VendorName, "Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.VendorName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.VendorName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.VendorPassword, "Password", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.VendorPassword, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.VendorPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.VendorEmail, "Email", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.VendorEmail, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.VendorEmail, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.VendorPhone, "Mobile Number", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.VendorPhone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.VendorPhone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.VendorAddress, "Address", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.VendorAddress, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.VendorAddress, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @*@Html.LabelFor(model => model.VWalletBalance, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.VWalletBalance, new { @Value = "0", Type = "hidden" })
                    @Html.ValidationMessageFor(model => model.VWalletBalance, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input style="margin-left:80px;" type="submit" value="Signup" class="btn btn-info" />
                </div>
            </div>
        </div>
    }

    @*<div>
            @Html.ActionLink("Back to List", "Index")
        </div>*@
    @*</body>*@

OnlineClothStore/Views/Vendors/Delete.cshtml
@model OnlineClothStore.Models.Vendor

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vendor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.VendorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VendorName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VendorPassword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VendorPassword)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VendorEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VendorEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VendorPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VendorPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VendorAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VendorAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VWalletBalance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VWalletBalance)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OnlineClothStore/Views/Vendors/Details.cshtml
@model OnlineClothStore.Models.Vendor

@{
    ViewBag.Title = "Details";
}
<h2>Hey @Model.VendorName</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VendorName)
        </dd>
        <br />
        <dt>
            Password
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VendorPassword)
        </dd>
        <br />
        <dt>
            Email
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VendorEmail)
        </dd>
        <br />
        <dt>
            Mobile Number
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VendorPhone)
        </dd>
        <br />
        <dt>
            Address
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VendorAddress)
        </dd>
        <br />
        <dt>
            Wallet Balance
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VWalletBalance)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit Profile", "Edit", new { id = Model.VendorId })
    <span> | </span>
    @Html.ActionLink("Back to Dashboard", "VendorDashboard")
</p>

OnlineClothStore/Views/Vendors/Edit.cshtml
@model OnlineClothStore.Models.Vendor

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VendorId)

        <div class="form-group">
            @Html.LabelFor(model => model.VendorName,"Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VendorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VendorName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VendorPassword,"Password", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VendorPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VendorPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VendorEmail,"Email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VendorEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VendorEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VendorPhone,"Mobile Number", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VendorPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VendorPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VendorAddress,"Address", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VendorAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VendorAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.VWalletBalance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VWalletBalance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VWalletBalance, "", new { @class = "text-danger" })
            </div>
        </div>*@
        @Html.HiddenFor(model=>model.VWalletBalance)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

OnlineClothStore/Views/Vendors/Index.cshtml
@model IEnumerable<OnlineClothStore.Models.Vendor>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.VendorName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VendorPassword)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VendorEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VendorPhone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VendorAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VWalletBalance)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.VendorName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VendorPassword)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VendorEmail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VendorPhone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VendorAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VWalletBalance)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.VendorId }) |
            @Html.ActionLink("Details", "Details", new { id=item.VendorId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.VendorId })
        </td>
    </tr>
}

</table>

OnlineClothStore/Views/Vendors/VendorDashboard.cshtml
@{
    ViewBag.Title = "VendorDashboard";
}
<br /><br />
<h2 id="signtitle"> Hey @User.Identity.Name</h2>

<br />
<br />
<br />
<br />
<div class="col-md-offset-2 col-md-10">
    <input type="submit" value="View Profile" onclick="location.href='@Url.Action("Details", "Vendors", new { email = User.Identity.Name })'" class="btn btn-success" />
</div>
<br />
<br />
<br />
<br />

<div class="col-md-offset-2 col-md-10">
    <input type="submit" value="Update Products" onclick="location.href='@Url.Action("ProductsByVendorId", "Products", new { email = User.Identity.Name })'" class="btn btn-success" />
</div>
<br />
<br />
<br />
<br />
<div class="col-md-offset-2 col-md-10">
    <input type="submit" value="View All Orders" onclick="location.href='@Url.Action("OrdersByVendorId", "Orders", new { email = User.Identity.Name })'" class="btn btn-success" />
</div>
<br />
<br />
<br />
<br />
<div class="col-md-offset-2 col-md-10">
    <input type="submit" value="Accept or Deny Orders" onclick="location.href='@Url.Action("VendorPendingOrders", "Orders", new { email = User.Identity.Name })'" class="btn btn-success" />
</div>
<br />
<br />