OnlineClothStore/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace OnlineClothStore.Models
{
    public class Order
    {
        [Key]
        public int OrderId { get; set; }
        public int CustomerId { get; set; }
        public int VendorId { get; set; }
        public int ProductId { get; set; }
        public int ProductQuantity { get; set; }
        public string OrderStatus { get; set; }
        public DateTime? OrderDate { get; set; }
        public float OrderTotal { get; set; }
    }
}

OnlineClothStore/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.VisualBasic.ApplicationServices;
using OnlineClothStore.Models;

namespace OnlineClothStore.Controllers
{
    public class ProductsController : Controller
    {
        private OnlineClothStoreDBContext db = new OnlineClothStoreDBContext();

        // GET: Products
        public ActionResult Index()
        {
            return View(db.Product.ToList());
        }
        public ActionResult ProductsbyVendorId(string email)
        {

            if (email == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int VendorId = (int)db.Vendor.Where(c => c.VendorEmail == email).Select(c => c.VendorId).FirstOrDefault();

            IQueryable<Product> product = db.Product.Where(p => p.VendorId==VendorId);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product.ToList());
        }
        public ActionResult ProductsbyVendorId_Var(int id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IQueryable<Product> product = db.Product.Where(p => p.VendorId == id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product.ToList());
        }

        public ActionResult UpdateOrderDetails(Product p)
        {
            Order order = new Order();
            {
                order.VendorId = p.VendorId;
                order.ProductId = p.ProductId;
                order.OrderStatus = "Pending";
                order.OrderDate = Convert.ToDateTime(DateTime.Now);
            };
            TempData["orderDetails"] = order;
            TempData["CurrentOrderProduct"] = p;
            return RedirectToAction("Create", "Orders");

        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
        public ActionResult DetailsName(string name)
        {
            if (name == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var product = db.Product.Where(p => p.ProductName.Contains(name));
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product.ToList());
        }
        // GET: Products/Details/5 ( Search By CategoryName)
        public ActionResult DetailsCategory(string category)
        {
            if (category == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var product = db.Product.Where(p => p.CategoryName.Contains(category));
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product.ToList());
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase file, Product product)
        {
            string VenEmail = Convert.ToString(Request["VendorEmail"].ToString());
            product.VendorId = (int)db.Vendor.Where(v => v.VendorEmail == VenEmail).Select(c => c.VendorId).FirstOrDefault();
            string filename = Path.GetFileName(file.FileName);
            string _filenameWtDate = DateTime.Now.ToString("yymmssfff") + filename;
            string extention = Path.GetExtension(file.FileName);
            string path = Path.Combine(Server.MapPath("~/ProductImages/"), _filenameWtDate);

            product.ProductImage = "~/ProductImages/" + _filenameWtDate;
            if (ModelState.IsValid)
            {
                file.SaveAs(path);
                db.Product.Add(product);
                db.SaveChanges();
                return RedirectToAction("ProductsbyVendorId_Var", new { id = product.VendorId });
            }

            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Product.Find(id);
            TempData["ProductImagePath"] = product.ProductImage;
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HttpPostedFileBase file, [Bind(Include = "ProductId,ProductName,VendorId,ProductQuantity,ProductPrice,ProductImage,CategoryName")] Product product)
        {
            if (file != null)
            {
                string filename = Path.GetFileName(file.FileName);
                string _filenameWtDate = DateTime.Now.ToString("yymmssfff") + filename;
                string extention = Path.GetExtension(file.FileName);
                string path = Path.Combine(Server.MapPath("~/ProductImages/"), _filenameWtDate);

                product.ProductImage = "~/ProductImages/" + _filenameWtDate;
                file.SaveAs(path);

            }
            else
            {
                product.ProductImage = (string)TempData["ProductImagePath"];
            }
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ProductsbyVendorId_Var", new { id = product.VendorId });

            }
            return View(product);
        }
        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Product.Find(id);
            int vendorId = product.VendorId;
            db.Product.Remove(product);
            db.SaveChanges();
            return RedirectToAction("ProductsbyVendorId_Var", new { id = vendorId });
   
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineClothStore/Controllers/VendorsController.cs
using Microsoft.AspNet.Identity;
using OnlineClothStore.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace OnlineClothStore.Controllers
{
    public class VendorsController : Controller
    {
        private OnlineClothStoreDBContext db = new OnlineClothStoreDBContext();
        private ApplicationDbContext db1 = new ApplicationDbContext();

        // GET: Vendors
        public ActionResult Index()
        {
            return View(db.Vendor.ToList());
        }

        // GET: Vendors/Details/5
        public ActionResult Details(string email)
        {
            if (email == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vendor vendor = (Vendor)db.Vendor.SingleOrDefault(c => c.VendorEmail == email);
            if (vendor == null)
            {
                return HttpNotFound();
            }
            return View(vendor);
        }

        // GET: Vendors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vendors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VendorId,VendorName,VendorPassword,VendorEmail,VendorPhone,VendorAddress,VWalletBalance")] Vendor vendor)
        {
            if (ModelState.IsValid)
            {
                db.Vendor.Add(vendor);
                if (!db1.Users.Any(u => u.Email == vendor.VendorEmail))
                {
                    var store = new Microsoft.AspNet.Identity.EntityFramework.UserStore<ApplicationUser>(db1);
                    var manager = new UserManager<ApplicationUser>(store);
                    var user = new ApplicationUser { UserName = vendor.VendorEmail, Email = vendor.VendorEmail };
                    manager.Create(user, vendor.VendorPassword);
                }
                db.SaveChanges();
                return RedirectToAction("VendorLogin", "Account");
            }

            return View(vendor);
        }

        // GET: Vendors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vendor vendor = db.Vendor.Find(id);
            if (vendor == null)
            {
                return HttpNotFound();
            }
            return View(vendor);
        }

        // POST: Vendors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VendorId,VendorName,VendorPassword,VendorEmail,VendorPhone,VendorAddress,VWalletBalance")] Vendor vendor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vendor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("VendorDashboard");
            }
            return View(vendor);
        }

        // GET: Vendors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vendor vendor = db.Vendor.Find(id);
            if (vendor == null)
            {
                return HttpNotFound();
            }
            return View(vendor);
        }

        // POST: Vendors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vendor vendor = db.Vendor.Find(id);
            db.Vendor.Remove(vendor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult VendorDashboard()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineClothStore/Views/Orders/Create.cshtml
@model OnlineClothStore.Models.Order

@{
    ViewBag.Title = "Create";
}
<br />
<br />
<h2 id="signtitle">We make your dream wardrobe!</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
                @Html.LabelFor(model => model.CustomerId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CustomerId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div class="form-group">
            @Html.LabelFor(model => model.VendorId, "Vendor ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.VendorId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VendorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, "Product ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.ProductId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductQuantity, "Quantity", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductQuantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderStatus, "Order Status", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.OrderStatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.OrderDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Enter Email for Verification")
            @*<div class="col-md-10">*@
            @Html.TextBox("CustomerEmail")
            @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            @*</div>*@
        </div>
        @*<div class="form-group">
                @Html.LabelFor(model => model.OrderTotal, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OrderTotal, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.OrderTotal, "", new { @class = "text-danger" })
                </div>
            </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Place Order" class="btn btn-success" />
        </div>
        <p>@ViewData["BalanceError"]</p>
    </div>
        <script type="text/javascript">
            function check() {
                alert("Order Placed Successfully!");
            };
        </script>

    </div>
}
<br />
<br />
<p>
    @Html.ActionLink("Back to Product List", "Index", "Products")
    <span> | </span>
    @Html.ActionLink("Back to Dashboard", "CustomerDashboard", "Customers")
</p>

OnlineClothStore/Views/Orders/CustomerHistory.cshtml
@model IEnumerable<OnlineClothStore.Models.Order>

@{
    ViewBag.Title = "CustomerHistory";
}

<h2 id="signtitle">Your Orders</h2>
<br /><br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CustomerId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VendorId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductQuantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderTotal)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VendorId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductQuantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderStatus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderTotal)
        </td>
    </tr>
}

</table>

OnlineClothStore/Views/Orders/Delete.cshtml
@model OnlineClothStore.Models.Order

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VendorId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VendorId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductQuantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductQuantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderTotal)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OnlineClothStore/Views/Orders/Details.cshtml
@model OnlineClothStore.Models.Order

@{
    ViewBag.Title = "Details";
}

<h3>Order Details</h3>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Customer ID
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerId)
        </dd>

        <dt>
            Vendor ID
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VendorId)
        </dd>

        <dt>
            Product ID
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductId)
        </dd>

        <dt>
           Quantity Ordered
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductQuantity)
        </dd>

        <dt>
            Order Status
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderStatus)
        </dd>

        <dt>
            Date Of Order
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>

        <dt>
            Order Amount
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderTotal)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to Dashboard", "CustomerDashboard","Customers")
</p>

OnlineClothStore/Views/Orders/Edit.cshtml
@model OnlineClothStore.Models.Order

@{
    ViewBag.Title = "Edit";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <br /><br />
    <h5>Click Accept to accept the order.</h5>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.OrderId)

    <div class="form-group">
        @Html.LabelFor(model => model.CustomerId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CustomerId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.VendorId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.VendorId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.VendorId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProductId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProductId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProductQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProductQuantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProductQuantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OrderStatus, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.OrderStatus, new { @Value = "Accepted" })
            @Html.ValidationMessageFor(model => model.OrderStatus, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OrderDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OrderDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OrderDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OrderTotal, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OrderTotal, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OrderTotal, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Accept Order" onclick="check()" class="btn btn-success" />
        </div>
    </div>
    <script type="text/javascript">
        function check() {
            alert("Order Accepted Successfully!");
        };
    </script>
</div>
}

<div>
    @Html.ActionLink("Back to List", "VendorPendingOrders", new { email = @User.Identity.Name })
    
    
</div>

OnlineClothStore/Views/Orders/Index.cshtml
@model IEnumerable<OnlineClothStore.Models.Order>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CustomerId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VendorId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductQuantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderTotal)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VendorId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductQuantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderStatus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderTotal)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.OrderId }) |
            @Html.ActionLink("Details", "Details", new { id=item.OrderId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.OrderId })
        </td>
    </tr>
}

</table>

OnlineClothStore/Views/Orders/OrdersByVendorId.cshtml
@model IEnumerable<OnlineClothStore.Models.Order>

@{
    ViewBag.Title = "OrdersByVendorId";
}
<br />
<br />
<br />
<h4 id="signtitle">Your Orders</h4>
<table class="table">
    <tr>
        <th>
            Customer ID
        </th>
        <th>
            Product ID
        </th>
        <th>
            Ordered Quantity
        </th>
        <th>
            Order Status
        </th>
        <th>
            Order Date
        </th>
        <th>
            Order Amount
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductQuantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderTotal)
            </td>
        </tr>
    }

</table>
<p>
@Html.ActionLink("Back to Dashboard", "VendorDashboard", "Vendors")
    </p>

OnlineClothStore/Views/Orders/VendorPendingOrders.cshtml
@model IEnumerable<OnlineClothStore.Models.Order>

@{
    ViewBag.Title = "VendorPendingOrders";
}
<br /><br /><br />
<h4 id="signtitle">Orders to be Reviewed</h4>
<p>
    @Html.ActionLink("Back to Dashboard", "VendorDashboard", "Vendors")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CustomerId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductQuantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderTotal)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductQuantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderStatus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderTotal)
        </td>
        <td>
            @Html.ActionLink("Accept", "Edit", new { id=item.OrderId }) |
            @Html.ActionLink("Deny", "EditForDeny", new { id=item.OrderId })
        </td>
    </tr>
}

</table>